# /:categories/:year/:month/:day/:title/
permalink:           pretty

# Setup
title:               Ben Mann
tagline:             'projects &c'
description:         'Read about my projects, maybe learn something, maybe lend a hand!'
url:                 http://8enmann.github.io
baseurl:             ''
paginate:            5
paginate_path: "page:num"
gems: [jekyll-paginate, jekyll-gist] 

# About/contact
author:
  name:              Ben Mann
  url:               https://twitter.com/8enmann
  email:             8enmann+io@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/8enmann
linkedin:            https://www.linkedin.com/in/benjamin-mann
